/**
 * Column conventions for every table in StockHub.
 *
 * Read this file once and the rest of the schema is predictable.
 *
 * 1. PRIMARY KEYS - `uuid` with `defaultRandom()` (Postgres gen_random_uuid()).
 *    Why uuid and not a text cuid/nanoid: the id is generated by the database,
 *    so a plain `INSERT ... RETURNING id` works from any runtime (Bun, the
 *    Worker, psql, a data fix) without pulling an id library into that runtime.
 *    It also keeps foreign keys narrow (16 bytes) and lets us pre-generate ids
 *    for the seed as literal strings. @stockhub/core ids are branded strings,
 *    and a uuid string satisfies that brand with `asVariantId(row.id)`.
 *    Trade-off accepted: uuid v4 is not time sortable, so every "newest first"
 *    query orders by a timestamp column, never by id.
 *
 * 2. MONEY - `bigint({ mode: 'number' })` holding an integer number of satang
 *    (1 THB = 100 satang). See packages/core/src/domain/money.ts.
 *    `mode: 'number'` returns a JS number instead of a BigInt, which is safe
 *    here: Number.MAX_SAFE_INTEGER is 9,007,199,254,740,991 satang, about
 *    90,071,992,547,409 baht. A Thai SME will not reach that. Wrap the value
 *    with `satang()` from core when it crosses into domain code.
 *    Never use `numeric`/`real` for money - float drift breaks FIFO layers.
 *
 * 3. TIMESTAMPS - always `timestamp with time zone`, stored in UTC, mapped to a
 *    JS Date. Marketplace exports print local Bangkok time with no offset, so
 *    the adapter converts to UTC before it reaches this layer.
 *
 * 4. MULTI-TENANCY - every business table carries `org_id` with an index, even
 *    when it could be reached through a join. It makes every query filterable
 *    by tenant and makes a future row level security policy trivial.
 *
 * 5. RELATIONS - drizzle `relations()` live in ./relations.ts, not next to the
 *    tables, so schema files never import each other in a cycle.
 */

import { bigint, timestamp, uuid } from 'drizzle-orm/pg-core';

/** Standard surrogate primary key. */
export const primaryId = () => uuid('id').primaryKey().defaultRandom();

/** A money column in satang. See rule 2 above. */
export const money = (name: string) => bigint(name, { mode: 'number' });

/** A point in time, stored with its timezone. */
export const tsColumn = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

/**
 * Spread into a table definition: `...timestamps`.
 * `updatedAt` is maintained by drizzle on every `.update()` call. If you write
 * raw SQL, set it yourself.
 */
export const timestamps = {
  createdAt: tsColumn('created_at').notNull().defaultNow(),
  updatedAt: tsColumn('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};
